-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgV7pzYPnw0GF6jjDi
SoJDkGi5At2mWk/9dL2YzgHU9eCgCgYIKoZIzj0DAQehRANCAARCMogmgEKRji1z
htfGxF5y4wpMQtkSTIGEs3alOAfFFlU+9TMoEU/is/jBmt5M/Guu9GVvU+YDZqOI
sofzjwzc
-----END PRIVATE KEY-----